php:
  # image: limogin/php-7-2-8-apache
  # build: .
  # restart: always
  container_name: php.test 
  build: . 
  ports:
    - "8084:80"
  volumes:
    - "./app:/var/www/html/:rw"
  # - "./backup:/backup/:rw"
  # links:
  #  - mysql
  environment:
    DOCKERENV: dev 
    APACHE_RUN_USER:   mark 
    APACHE_RUN_GROUP:  mark 
    SITE:      limogin.com
    SITE1:     limogin.com


    



